language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: 4rcq2sClZgPQygSrNNFEolARwzBdeouAFAW0RnbmyxrkUi0+YZ7YyCu0k4c2qlJd6cAADQ7dpQs1GyoCX5aLvzFK7HxQvoXl6o5dd8kJHBKW5JowIH4/jdjrh8tooRo1IGfk9unOjvgzSZMCdkY3JvnFpgn3sSzm2sWFBiO+Xe3Uwri1l51CP/k3oC85zXpjcJ7SQHdf2Za9GlNtht8A/NsuglDQU0r4ZXn/Qcti4OcgnQKR7xEspvVLiUoF+LwQTR2JyuiBrleTAIwfJMj7Cq8ZP0Jf+rvhYOaX2eHLW8w8owOqdZUhjxPe9neHGCPYVaisfeixXerQkvWQiYCSNUGtGcv3reQMTHoB2b40FIqdZ1Vnp5Sj5uSSvm/wIZhLRnMBqYZBO3vA5f/yuXZBMQEX++Cwhmy4TcBmM1u/RRqA41s5DLhbXveeoH+kMZ4G0w0vBZZ/O+xo02Bgpat/JKBzwOPmW8LbURSJgwBEwObM34rJ42Bv9qVH1vw/kAzUGl+vJQ/n32Jz7FInIg6fx11PJ2s8IalqNN2zFCSnFPSEqhvpm9PzsPkr7WXfJ1imN77laHUKmxUhEYWzgDgSDarGwYzNeHU/FYmRMB2lMFFZ66W4RrZJsSOHAr0dWtXGH1z2LBOrkqyGOBgkkZCpLFbc72RoTxJg4Y3989v/JvA=
  app: devops-apresentacao
  edge: true
