language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: E93l6UcszalxlNKZynk7/4JAy2fMjKFl5mN2Gbz3IcFkbHIJFhXtGVf4ogBELGFzWsFM9NQZUES7QPRebotAVvge54UJ9TKo455PtGBelQPTMjbXVRbapGH85vMi/2ECEAC8vRd8/+HUI5AP6PxYH9UORBN9dLXZxlxWkr3J3ihzyI+5E/UFYiY6ZfH2Tinb43x5p5LvDT/x96EWWIWNVcEN5x4VfG29R8g3SDr2+/uunv40CCm5ze+UqxYVkfr3gfPkw4uIGEx15rVUz/Xgr8hzludi/ahIhmNC2scZKMqPy2UNw/0Biwg0o+oj/RKb3FOK9Lenq9sWYAE+HXgi86u8oo+LeL1m07UsiGyA/TAAHv27eAQ5BKXYGos4bOWWW9ba3S0Vttem7wpFlAgJbNfoeVlK6d2JfkEldjRR6PW2c1tr4gH/u1mTNGj6PQljIOMRsY1BKLk6ihq/Dwu7CrvMaPrr/XqV9ixXhggi3TTZoui/L9u1bEBPvvi/umcTNYWatA8Gc4629stGT7Kx7fKZEGCmwIBsp3ztGokgU9t9BFz6W5eaRz5D8LWXJNG54wLQM5Oa31C1tx96dnAKH2PX6zV+eKAQzsfvkPexOTDQQsIBYVPBEHI248tN3ElMjiIz9eA+hE3k1sjJ0dWZyvlkhk/qz4MhMRlK5btjn1E=
  app: devops-apresentacao
  edge: true
