language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key: DiS4iY+wGXaUInU4Fr/YRmsIZHls4b+GkepHyU2ZpklmeVYy2CR+vWM9TpvCjZEyGzlqYjDon4O0oFmSNhNizBYutBm5+u6Wtk1KqwvPJpE8tUy8990xsqeMQjuu1vL84o1340nTLwi21dkB3woiPacRjsOUwtvXzflVKycxAPwdiHDZ2a6B839r/nYgJWMmZSgIvkvV/E2VkoVAgaf2VSEZnudokpRyYtrqmggJqbica2f1Ap7d5/TP606cnxQswNbnXxsyXDgC+wxp8c+tarFG6n5bpRT+wQz9qJ94xjPZ2DDqrRPQeiEyNg6r7MTa9qDjfVMOts8nSuwG5l4wKSMUr1PmNz53OA9P6tYyM8zqZamA7BT778JiCtzdAaI1DMi9apXGGchnS7wqAg81QaQ9xp94zwckuN7sCrviOL9wcEtcDIuqRs69EkSk0MggEbxxtE0x6EAYTu3Gyb9UBRgN0ywR4E7VL+iBc528uxYGoX5IJf5r/d95J8coM0aVOx4tH4DK7fLgKN3jEx770Ypv/nWQdMT43rmQkgcYfy8Af0pxGEnmlL/A8Nxkr5abMGUnjho8w3sRemZCvqg9hfaCiGFrDIo0UYvbpscYBDsLIL54AZFbtnpvVI5O75/uak+RfPQgIeLXSQiIkE/lgYNOucSOoTH+K7Ekrj480qg=
  app: devops-apresentacao
  edge: true