language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: cSpzWt3bjeMsgZr88GNkLNqATwHjfAUkky20NQX328eCwcRQEWdY9SAnVYY1sUOQycY2UAZ6lfwgS+35CFd0rtqep8PeK1dsLnHzMdncpsvD6apYYbx9Fu/t9sRtyY5kt1aOcQGClF6/2qC/WYf2eqnOAqv300p3aeSrlAHbE9uezJC07Yp4ki8Ba+cjNtTmdXE0EVBvgLS9x9nC3tvCsk54mQMxYCt/SY1BhzK9D89nlO6zhEZWBmMegMpsY+qngo0JVsMewypPO+4U2yP2/dbUO2p88tcsa7JnNfWQODZJBKC58vET3BCKxMaaE+zNUEB5mpiDCulQJzF9c/q1dWNikhmirhpK9PDMUmLfsgT4QnRQqnDrG0sfiyAoPSBnOBE2HdCOYjrjNFzw+XHOfCeyc16AbMOQEXULWAi7IwYqsXOfPzrFkl9VAsl73u3zOaSkVTm2k3HdQIjY17IDd1agq+D9Ug2sB853M/FqsVHV7Qk4rTegYLQnSezQI7aRRtKkTGzNH3CtT2wX3y6AyOnYcWC8kKc5DDAu8I8+hXSOALKmQ9sRFE9BFmcPvhpPdB2LH5hJLchgZQURut4vTMCUlosX7tQ9RNK2d91HrMY7a/9V2cCTVigkGD30qkThhGXsUg8oHfYxw8FRGQpItjE5cSCgG+PfU10wfDjDdj4=
  app: devops-apresentacao
  edge: true
