language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: kz/5LNQE82H1EznaQ5Jh08vCV9ziIk3zJDvSyT3bLNH3fX3PHsBIjJ8MbuIgVG9XhYiIcvMlNO9yzdcHCNYeF/MRS38/sH0LXHJGioRnV+EafqfHeKF00PG+8+wTZsUSNX1oqvIGkF0aRaK2PSQPabj2npgJ8pickX9lvZsKOhCYJocBrxbT7WS7g59UUQit44awEDJ1SGlPtDGbNBmZcw+e++Wb5lcNQQ/arahBUX4aJxRj3LQWE3+lgU+BqZUxzW42EXWV7Lnk7S8T6hmVM/Jt3J4m99rFQtPsaHzpgvbPqt5eRsH2UYO8BVSxsWOzbtu8UFSLh+Nz7k1f7suB2jcKwTeHqfqB6/Dy+7Np06ZYDw6lC1ytBJE7tMmRx2IV83OeJ3jgdkaw29LZyQEbtPjCFDbzCPoCzrAQ3/iz5/1RBaUmwArkgMyI6COZht2s5hJ31K6c5itKgcFaIp2zOcH2McEvdxyxw6ia4i6DXYOLpy6NrE10A070jo+9JpJ649G714gVvWe2/Mxx4k55SegFMvcOq2uvdxSpgXAIfopBaJlNXm6+NIqcssNthfrNl6fXegIHHZnPtlcs2rH/D9gqoPtcmZwYyj3Y7k8LXyefU0eUFMWtrjXkZQhcpmTzVURcvNlr7456HLuSwKJmJluIhdWGOdsHT7fzPj3ajt8=
  app: devops-apresentacao
  edge: true
