language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: TE3hDMOGFQbYv2zXWX0mwGpKlo9QWrXldMuAZhesBizUiyIh9nAXWeGxIO3m0KYdzZTiFwtd8j78se/4DwHKOpmG+hDYkRjPNbqv0LTxOZPAzDd+X5UIu0b8Rg+KJ3lFXSy5VIMMtAN14Okbk6hMhoq0Tg3039mL0PZg+vxLJy3/iQwk5zWaXBZLR9DyneL8BlAocy9tQqxVRwaJVNo/30RdzL008xlnyvkiJpHxjItc6snS0zv5QFLBhhjCw58I21ZhHt7S1Yrgn1hgIResk8sr7K3jqjIPHbk6Hx6vWr4Hwi9zzZl+KAeSo3kV2Ap4+ydw1xLciVtiiG6iRjLVlBR0Nkr/twFtLTbNGNSuuxW47nTEosBebWLUG2zPWp5aaTyW3w7bdBD4OOtbE7wBv4V5helsBtN9GqgHWBxlB7/ZO4x2WW8Drv5aoVb2chytMmnF+XYJ1ispEzakpyG5BstBiCgZ/BtkwJoI/iqc6RmjynU+zkDoHratys3mMiE5WV7OJEg8ECKzEjsYTpagaBNk9O09et7L2JB8zwgqvhTwYj0QFztmpMFjr7qRh8jg0PbsVExhxksNAtBnqkxrSOhPFBqBqLtj6MFTQqevsD+M+lOkHcj/Hk3Wetks3Z4tuSb2zTHLq3x68MIYqC7tQzEmTd6Mz/dvd4m9AQxvrLg=
  app: devops-apresentacao
  edge: true
